#ifndef CIPTABLES_H
#define CIPTABLES_H

#define SUCCESS 0
#define ERROR_GENERIC_ERROR -1
#define ERROR_UNINITIALIZED -2
#define ERROR_UNSUPPORTED_OPERATION -3
#define ERROR_NOT_IMPLEMENTED -4
#define ERROR_ILLEGAL_ARGUMENTS -5

#define TABLE_NAME_IDX 1
#define CMD_NAME_IDX 2

#endif